FROM alpine:latest AS certs

RUN apk add --update --no-cache \
  ca-certificates && \
  update-ca-certificates

FROM ARG_FROM

LABEL maintainer="info@thingful.net"
LABEL description="Datastore for DECODE IoT Pilot"

COPY --from=certs /etc/ssl/certs /etc/ssl/certs

ADD bin/ARG_ARCH/ARG_BIN /ARG_BIN

USER nobody:nogroup
ENTRYPOINT ["/ARG_BIN"]
